### ISSUE TITLE
Where can I get the GENEMANIA_LUCENE_INDEX_DIR data,please help me

### ISSUE THREAD

**Issue by xzhou89** [GeneMANIA/genemania#205] opened 2023-06-26 09:16 UTC
when I start it show 

 ERROR ApplicationConfig:63->	 . GENEMANIA_LUCENE_INDEX_DIR : null

Where can I get the GENEMANIA_LUCENE_INDEX_DIR data

**Comment by chrtannus** [comment] 2023-07-24 17:58
Duplicate of #203

**Closed by chrtannus** 2023-07-24 17:58 UTC
Labels: duplicate
